#lang slideshow

(require "../lib/lib.rkt")
(require "clang-repl.rkt")
(require "title.rkt")
(require "demo.rkt")
(require "tab-event.rkt")
(require "regular.rkt")
(require "first-attempt.rkt")
(require "new-attempt.rkt")
(require "visibility-of-decls.rkt")
(require "new-context.rkt")
(require "original-plan.rkt")
(require "how-sema-works.rkt")
(require "contributions.rkt")
(require "sumup.rkt")
(require racket/draw)

(module+ main
  (current-page-number-font (make-object font% 25 'default))
  (main-title)
  (title-only-slide #:title "What is ClangRepl")
  (what-is-clang-repl)
  (title-only-slide #:title "Demo")
  (demo)
  (contributions)
  ;; (title-only-slide #:title "Steps")
  (visibility-of-decls)
  (new-context)
  (title-only-slide #:title "Semantic Code Completion" #:font-size 40)
  (what-sema-comp-needs)
  (how-sema-works)
  (title-only-slide #:title "Implementation")
  (first-attempt)
  (new-attempt)
  ;; (filter-candidates)
  (conclusions))
