#lang slideshow

(require "../lib/lib.rkt")
(require "clang-repl.rkt")
(require "title.rkt")
(require "demo.rkt")
(require "tab-event.rkt")
(require "regular.rkt")
(require "first-attempt.rkt")
(require "new-attempt.rkt")
(require "visibility-of-decls.rkt")
(require "new-context.rkt")
(require "original-plan.rkt")
(require "how-sema-works.rkt")
(require "contributions.rkt")
(require "sumup.rkt")

(module+ main
  (main-title)
  (title-only-slide #:title "What is ClangRepl")
  (what-is-clang-repl)
  (title-only-slide #:title "Demo")
  (demo)
  (contributions)
  ;; (title-only-slide #:title "Implementation")
  ;; (tab-event)
  ;; (regular)
  ;; (first-attempt)
  ;; (new-attempt)
  (title-only-slide #:title "Challenges")
  (visibility-of-decls)
  (new-context)
  (title-only-slide #:title "Semantic Code Completion" #:font-size 40)
  (original-plan)
  (how-sema-works)
  ;; (filter-candidates)
  (sum-up)
  (title-only-slide #:title "Q & A"))
