#lang slideshow

(require "../lib/lib.rkt")
(require "title.rkt")
(require "motivations.rkt")
(require "tab-event.rkt")
(require "regular.rkt")
(require "first-attempt.rkt")
(require "new-attempt.rkt")
(require "visibility-of-decls.rkt")
(require "new-context.rkt")
(require "original-plan.rkt")
(require "how-sema-works.rkt")
(require "filter-candidates.rkt")
(require "sumup.rkt")

(module+ main
  ;; (main-title)
  ;; (title-only-slide #:title "Motivations")
  ;; (motivations)
  ;; (title-only-slide #:title "Implementation")
  ;; (tab-event)
  (regular)
  (first-attempt)
  ;; (new-attempt)
  ;; (title-only-slide #:title "Problems")
  ;; (visibility-of-decls)
  ;; (new-context)
  ;; (title-only-slide #:title "Semantic Code Completion")
  ;; (original-plan)
  ;; (how-sema-works)
  ;; (filter-candidates)
  ;; (sum-up)
  #;
  (title-only-slide #:title "Q & A"))
